info:
  title: WolframAlpha LLM API
  description: API for querying WolframAlpha for natural language queries and computational knowledge results.
  version: 1.0.0
servers:
  - url: https://www.wolframalpha.com/api/v1
paths:
  /llm-api:
    get:
      summary: Submit a query to WolframAlpha LLM API
      description: Submit a natural language query with an AppID and input to WolframAlpha.
      parameters:
        - name: appid
          in: query
          required: true
          description: The WolframAlpha AppID used for authenticating the request.
          schema:
            type: string
        - name: input
          in: query
          required: true
          description: The URL-encoded input query string.
          schema:
            type: string
        - name: maxchars
          in: query
          required: false
          description: Maximum number of characters to be returned in the response. Defaults to 6800 characters.
          schema:
            type: integer
        - name: assumption
          in: query
          required: false
          description: List of assumptions to refine the query.
          schema:
            type: array
            items:
              type: string
        - name: ip
          in: query
          required: false
          description: IP address of the query origin.
          schema:
            type: string
        - name: latlong
          in: query
          required: false
          description: Latitude and longitude for location-based queries.
          schema:
            type: string
        - name: timezone
          in: query
          required: false
          description: Timezone for the query.
          schema:
            type: string
        - name: units
          in: query
          required: false
          description: Preferred units for result data (e.g., metric or imperial).
          schema:
            type: string
        - name: currency
          in: query
          required: false
          description: Currency code for financial queries.
          schema:
            type: string
        - name: languagecode
          in: query
          required: false
          description: Language code for the query input and response.
          schema:
            type: string
        - name: formattimeout
          in: query
          required: false
          description: Timeout in seconds for formatting the response.
          schema:
            type: integer
      responses:
        '200':
          description: Successful response with results from WolframAlpha.
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: string
                    description: The query that was submitted.
                  inputInterpretation:
                    type: string
                    description: WolframAlpha's interpretation of the input query.
                  result:
                    type: string
                    description: The computed result for the query.
                  images:
                    type: array
                    items:
                      type: string
                    description: List of image URLs related to the query.
                  link:
                    type: string
                    description: A link back to the full WolframAlpha results page for this query.
        '400':
          description: Bad request, input parameter is missing or invalid.
        '403':
          description: Invalid or missing AppID.
        '501':
          description: Input cannot be interpreted by the API.

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: AppID
security:
  - BearerAuth: []
